import {CID_ALGORITHM_CODES, CID_ALGORITHM_NAMES} from "@root/hash-compute/MultiHashData";

export const codeTable = {
    [CID_ALGORITHM_NAMES.crc32]: CID_ALGORITHM_CODES.crc32,
    [CID_ALGORITHM_NAMES.md5]: CID_ALGORITHM_CODES.md5,
    [CID_ALGORITHM_NAMES.sha1]: CID_ALGORITHM_CODES.sha1,
    [CID_ALGORITHM_NAMES.sha256]: CID_ALGORITHM_CODES.sha256,
    [CID_ALGORITHM_NAMES.sha3_256]: CID_ALGORITHM_CODES.sha3_256,
    [CID_ALGORITHM_NAMES.sha3_384]: CID_ALGORITHM_CODES.sha3_384,
    [CID_ALGORITHM_NAMES.midhash256]: CID_ALGORITHM_CODES.midhash256,
    [CID_ALGORITHM_NAMES.btih_v2]: CID_ALGORITHM_CODES.btih_v2
}