import {SimpleFileType} from "../SimpleFileType.js";

export const extensionMappings: { [key: string]: SimpleFileType } = {
    // Audio
    'mp3': 'audio',
    'wav': 'audio',
    'flac': 'audio',
    'aac': 'audio',
    'ogg': 'audio',
    'm4a': 'audio',
    // Video
    'mp4': 'video',
    'mkv': 'video',
    'webm': 'video',
    'avi': 'video',
    'mov': 'video',
    'wmv': 'video',
    'flv': 'video',
    'm4v': 'video',
    'mpg': 'video',
    'mpeg': 'video',
    '3gp': 'video',
    '3g2': 'video',
    'f4v': 'video',
    'm2ts': 'video',
    'mts': 'video',
    'ts': 'video',
    'vob': 'video',
    'ogm': 'video',
    'divx': 'video',
    'xvid': 'video',
    // Document
    'pdf': 'document',
    'doc': 'document',
    'docx': 'document',
    'ppt': 'document',
    'pptx': 'document',
    'xls': 'document',
    'xlsx': 'document',
    'txt': 'document',
    'rtf': 'document',
    // Images (are document)
    'jpg': 'document',
    'jpeg': 'document',
    'png': 'document',
    'gif': 'document',
    'bmp': 'document',
    'tif': 'document',
    'tiff': 'document',
    'svg': 'document',
    'webp': 'document',
    // Archive
    'zip': 'archive',
    'rar': 'archive',
    '7z': 'archive',
    'tar': 'archive',
    'gz': 'archive',
    'bz2': 'archive',
    'xz': 'archive',
    //subtitles
    'srt': 'subtitle',
    'sub': 'subtitle',
    'sbv': 'subtitle',
    'vtt': 'subtitle',
    //torrent
    'torrent': 'torrent',
};